### ISSUE TITLE
E1.2 - Scaling of performance - function_time_against_n

### ISSUE THREAD

**Issue by davidfof13** [HPCE/hpce-2014-cw1#10]
Hi 

Your syntax error in the description of "function_time_against_n" confuses me : "The total time used to calculate calculate times should be (approximately) bounded by the maxTime parameter. " Can you please clarify if maxTime is the maximum time taken to run function_time_against_n or the maximum time taken to run the passed function, f?

Thanks

**Comment by m8pple** [comment]
It's the former, so the maximum time spent across all functions - simply put, the amount of time
the user is willing to spend probing larger values of n.

Thanks, I'll update the text.
