### ISSUE TITLE
matlabpool error- R2014b on Ubuntu 12.04

### ISSUE THREAD

**Issue by threewholefish** [HPCE/hpce-2014-cw1#11]
Undefined function 'matlabpool' for input arguments of type 'char'.

Error in timing.plot_function_time_against_n (line 49)
matlabpool SIZE;

Apparently this is not a problem on R2014b on Mac, or R2014a on Windows. It tells me that matlabpool will be removed, and to use parpool instead.

**Comment by m8pple** [comment]
I had some problems with that during christmas, I thought I'd managed to get portability
across the versions. Oh well.

The above commit attempts to adapt to either method. Can you pull it and see if that works?

**Comment by threewholefish** [comment]
that's fixed it, thanks

**Comment by darioml** [comment]
Just gotten this again now on Mac_R2014b. Will look into it and look for a workaround.
