### ISSUE TITLE
quality of image filters

### ISSUE THREAD

**Issue by davidfof13** [HPCE/hpce-2014-cw1#13]
Hi

Do you expect our filters to give the same results as yours? meaning must our resulting image be identical to your reference output? This is what I get for the scharr kernel:

![cameraman comparison](https://cloud.githubusercontent.com/assets/5803443/5883120/5a5f1948-a347-11e4-89ba-2cb08da3cbac.jpg)

**Comment by darioml** [comment]
I'll leave @m8pple to confirm, but I would suspect identical results. In `README.md`, he mentions `Use the reference image as a comparison against yours. You can easily load images and subtract them.`

After (a lot of) messing around I managed to actually get the result.

I might be wrong, but it looks like your image there isn't showing vertical edges (look at the building in the background)

**Comment by davidfof13** [comment]
yes you're right. I noticed those differences that's why I wanted to check how well it had to match the reference output. But thanks for letting me know that it's actually possible to get an identical image.

**Comment by davidfof13** [comment]
Ok. I managed to obtain perfect results as you can see below and I passed all your basic tests but when I compare the reference and my output by doing "assert(all(all(ref==out_im)))", the assertion fails. What am I doing wrong?

![cameraman result perfect](https://cloud.githubusercontent.com/assets/5803443/5890045/c5999232-a43d-11e4-93a7-ce7f594e40b7.jpg)

**Comment by kronocharia** [comment]
Actually I have the same issue, a lot of my pixels are out by around  one brightness level
![screen shot 2015-01-25 at 10 02 20](https://cloud.githubusercontent.com/assets/3238456/5891098/510fb9c8-a479-11e4-9285-4a5947b97715.png)

**Comment by darioml** [comment]
Note the saved image has been saved as a PNG which is lossy. Just think `uint8(0.6018*255)` won't be the same as `double(153/255)`. 

I compared my image by taking my generation, and converting it to uint8.

**Comment by kronocharia** [comment]
Isn't png lossless?

**Comment by kronocharia** [comment]
But yeah, converting using im2uint8(generated) appears to solve the issue

**Comment by darioml** [comment]
PNG can be lossless, but not the way it's being used here

**Comment by m8pple** [comment]
The expectation was that people could get exactly the same results, and the idea of giving
the reference image was to try to make that process easier (last year people had difficulty
working out what the output should be in many circumstances). However, it didn't occur
to me that the hidden format conversion would be confusing to many people.

I've modified the language to be:

```
all(all( abs(ref - out_im) < 0.01 ) )
```

Hopefully that adds enough slack?

**Comment by davidfof13** [comment]
Thanks guys I converted the generated image with im2uint8  and the assertion passes.
