### ISSUE TITLE
CW1 submission link

### ISSUE THREAD

**Issue by bwh10** [HPCE/hpce-2014-cw1#14]
I understand that we are supposed to submit the courseworks on blackboard. However, I cannot find the submission link for the first coursework due next Tuesday 27 Jan. The "assessments" link is non-existent. 

![image](https://cloud.githubusercontent.com/assets/10518447/5887981/80015c2c-a3e4-11e4-9ec8-0826c2cd6c70.png)

**Comment by m8pple** [comment]
Ah, that would be why no-one has submitted yet. I checked all the coursework submissions
were visible from the student view, but it never occurred to me that the link itself would be hidden.

It is now visible. Thanks for that.
