### ISSUE TITLE
5.2 Parfor Ordering 

### ISSUE THREAD

**Issue by kronocharia** [HPCE/hpce-2014-cw1#18]
In 5.2  you suggest to just append the various local outputs to out, but the documentation for parlors warn that 
"Because of independence of iteration order, execution of parfor does not guarantee deterministic results."

yet the result comes out correct? So does parfor respect the ordering of the for loop whilst yet doing it in any order?

**Comment by m8pple** [comment]
You're right that in general this doesn't really meet the requirements for a classic
parallel-for loop, but my understanding is that they have [special-cased reductions](http://uk.mathworks.com/help/distcomp/reduction-variables.html) of this type as they are so common.

So as long as we do something that looks like:

```
x=[];
parfor i=...{
  part=something(i);
  x=[x ; part]
}
```

then it should be ok. Or at least, that is my interpretation, and it always seems to work.

In C++ and OpenCL we won't be able to do that, and have to be much more careful
about making sure that reductions are always associative and commutative.

**Comment by m8pple** [comment]
Closing for tidyness.
