### ISSUE TITLE
E1.1 Reliable timing

### ISSUE THREAD

**Issue by AugustineTan** [HPCE/hpce-2014-cw1#2]
I would like to clarify how much of the built-in MATLAB functions are we allowed to use? In this case there is a function timeit which could be use to deal with "fast" functions. Is it okay to use the function or write our own code?

**Comment by m8pple** [comment]
For assessment purposes, anything in the matlab standard library is fine,
so if you find a library function and it meets the specs, then it is a valid solution.

However, I would recommend you work out what the function is
doing, and moreover _why_ it is doing it. Standard libraries in matlab
are commented quite well, and often contain links to further reading.

Personally I would still also roll my own based on tic and toc, as it is easier
to see what it is doing and check I understand what is going on, but it
isn't required.
