### ISSUE TITLE
Saving Figures

### ISSUE THREAD

**Issue by AugustineTan** [HPCE/hpce-2014-cw1#3]
I would like to clarify about saving the figures as pdfs. Due to the size restriction of each pdf does that mean it is one figure to one pdf? Or can we include multiple figures in the pdf? Assuming we are only allowed one pdf for that question.

Also there is a mismatch in the name for saving the figure in section E1.2 of the README (e1_2_comparison.pdf) and prepare_submission.m (e1_2_scaling.pdf). Which one should be used?

**Comment by m8pple** [comment]
I didn't really imagine more than one plot per pdf, but if you want to do sub-plots for your own interest, then go for it. Assuming you save your figure in a vector format (which I think matlab does by default), then it takes a certain amount of effort to go over 256KB.

Thanks for pointing out the typo - I introduced the prepare_submission.m script as
a way of trying to define a specification which is more robust to typos as I write
the specification, which seems to have worked.
