### ISSUE TITLE
Sobel Kernel

### ISSUE THREAD

**Issue by kronocharia** [HPCE/hpce-2014-cw1#5]
<s>You suggest to start out with the blur kernel, but don't 3x3 neighbourhoods mean a 9x9 around the pixel instead of a + shape (or are you using a blur kernel with 0's in the four corners). </s>

<s>y_kernel = [ -1 -2 -1;
              0  0  0; 
              1  2  1];  

<s>G_y = sum(sum(y_kernel.\* in)); </s>

<s>Something like that should apply the kernel to the nhood using inplace multiplication right? Is writing it as you do in blur faster to run? But  mind you, I fail tests 2 and 3 of your simple example taking this approach. It does find edges, but nowhere near as sensitive as the reference image. </s>

<i>Edit: Ok so you used the 3 10 3 version of the sobel kernel it seems...</i>

Also, why do we divide by 8, arent there 9 multuplications we sum up?

G = sqrt(G_x^2+G_y^2)); has an extra trailing bracket it doesnt need.
And you seem to call the function median_scalar in examples, but ask for it to be named median_filter

**Comment by m8pple** [comment]
Well, it's the Scharr rather than Sobel, as it tends to look better on non axis-aligned edges (I think).

The division by 8 is purely for aesthetics (it looks nice). If you wanted to go for something technically correct, then it would depend on the sum of the weights, rather than the number of weights.

**Comment by m8pple** [comment]
You're right about median_filter.m being wrong. I'll stick with what "prepare_submission.m" asks for, and the rest of the document.
