### ISSUE TITLE
E2.2 Median Window Scaling

### ISSUE THREAD

**Issue by skong125** [HPCE/hpce-2014-cw1#7]
In the last part of this exercise you ask us to run 

f1=@(n)( render.apply_scalar( @effects.median_scalar, n, rand(100) ) );
f2=@(n)( render.apply_scalar( @effects.median_scalar, 4, rand(96+n) ) );
timing.plot_function_time_against_n( {f1, f2}, 4:1000 )

For me on my laptop, the default max time of 3s is not enough to show much information on the graph. I am only able to capture 3 points before timing out. Should I scale the max time up (~10s) so that more data points can be captured, such that there is more to see? Otherwise it looks like this:

![e2_2_median_window_scaling](https://cloud.githubusercontent.com/assets/8421326/5791240/94c669b0-9ebf-11e4-9605-4f314b3096a5.png)

**Comment by m8pple** [comment]
Yes, definitely play with the parameters to explore the shape. Also, you could look at reducing image size if you are having difficulty getting many points.

Also, note the comments in #9 about what happens for large image sizes.
